nums/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zad/', include('zad.urls', namespace='zad')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zad/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^random/$', views.random_number, name='random'),
]

zad/models.py
from django.db import models

# Create your models here.

zad/forms.py
from django import forms
from django.core.validators import RegexValidator

numeric = RegexValidator(r'^[-0-9][0-9]*$', 'Mozesz wprowadzac tylko liczby calkowite')

class NumberForm(forms.Form):
    number = forms.CharField(label='number', max_length=13, validators=[numeric])

zad/views.py
import random

from django.shortcuts import render

from zad.utils import word_generator
from .forms import NumberForm


def index(request):
    if request.method == 'POST':
        form = NumberForm(request.POST)
        if form.is_valid():
            number = form.cleaned_data['number']
            form = NumberForm()
            label = word_generator(number)
            return render(request, 'zad/index.html', {'label': label, 'form': form, 'number': number})
    else:
        form = NumberForm()
    return render(request, 'zad/index.html', {'form': form})


def random_number(request):
    if request.method == 'POST':
        form = NumberForm(request.POST)
        if form.is_valid():
            number = form.cleaned_data['number']
            form = NumberForm()
            label = word_generator(number)
            return render(request, 'zad/index.html', {'label': label, 'form': form, 'number': number})
    else:
        form = NumberForm({'number': random.randrange(-99999999999, 999999999999)})

    return render(request, 'zad/index.html', {'form': form})

zad/templates/zad/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{%  block title %}Nums zadanie {% endblock %}</title>

</head>
<body>
    {%  block content %}
    {% endblock %}
</body>
</html>

zad/templates/zad/form_template.html
{% extends 'zad/base.html' %}

{%  block content %}
    <form action="/number/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
{%  endblock content %}

zad/templates/zad/index.html
{% extends 'zad/base.html' %}

{%  block content %}
    <p>Program konweruje liczby calkowite od -999 bilionow do 999 bilionow na zapis słowny.</p>
    {% if number %}
        {{ number }}: {{ label }}
    {% endif %}
     <form class="form-horizontal"  action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'zad/form_template.html' %}
    </form>
    <a href="{% url 'zad:random' %}"><button type="button">losuj</button></a>
{% endblock %}